### ISSUE TITLE
Requires opening public port 9320 to use public SSL

### ISSUE THREAD

**Issue by paularmstrong** [stanford-oval/almond-hassio-repository#6]
Use case: I would like to only be able to access Almond internally on my network or through hassio ingress

Steps to reproduce:
1. Add the repository
2. Install the addon
3. Go to the web UI for Almond
4. Click "Click here to access"
5. A new browser tab opens with https://my-home-assistant.public.domain:9320

Expected:
Almond works in the ingress tab or via http://homeassistant.local:9320

When attempting the local http protocol using port 9320, an NGINX error is given:
> 400 Bad Request
> The plain HTTP request was sent to HTTPS port

I do not want to open port 9320 and only want Almond available using Hassio ingress or via my local network

Currently, the only way to access Almond is to open port 9320 in my firewall

**Comment by gcampax** [comment]
Unfortunately, the Home Assistant OS ingress is at the moment incompatible with OAuth, so we cannot make the full UI available in it (it would break Spotify, among other skills). This is a known limitation, and we're discussing with the Home Assistant developers what's the best way to move forward.

**Comment by bramkragten** [comment]
[httpS://homeassistant.local:9320](https://homeassistant.local:9320) should work for you if you ignore SSL errors, or maybe change the SSL options to non-existing paths.

It seems that the addon checks if cert files are present at the given path, and if so it runs in https, and otherwise of HTTP.

I had some old unused cert files in my `/ssl` folder and it used those, resulting in failed communication between the server, after removing those I could use http://homeassistant.local:9320, and it was working.
